[build]
  publish = "."
  command = "echo Build skipped"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions."playlists"]
  runtime = "python3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
